### ISSUE TITLE
Game crashes when I try clicking an item in inventory.

### ISSUE THREAD

**Issue by jgeekw** [ModdingForBlockheads/Forbic#31] opened 2022-07-29 17:04 UTC
### Minecraft Version

1.19.x

### Mod Loader

Forge

### Mod Loader Version

41.0.61

### Mod Version

4.3.0

### Describe the Issue

When I press E to open inventory and I try moving an item from inventory to hotbar, or just click any item, the game crashes and takes me back to the main title screen
[crash-2022-07-29_12.59.35-client.txt](https://github.com/ModdingForBlockheads/Balm/files/9221966/crash-2022-07-29_12.59.35-client.txt)
.

**Comment by Hxrlio** [comment] 2022-08-02 13:59
Player on my server had the same crash in 1.18.2 (forge 40.1.68, balm 3.1.0+0, CT 14.0.3)

**Comment by Hxrlio** [comment] 2022-08-02 14:05
Seems to be a 1 time issue thusfar

**Comment by Hxrlio** [comment] 2022-08-02 14:23
I think it has something to do with this not working as intended
Balm.getEvents().onEvent(ClientStartedEvent.class, event -> keyTransferStack = event.getMinecraft().options.keyUp);

@ line 51 of net.blay09.mods.craftingtweaks.client.ModKeyMappings.java

**Comment by BlayTheNinth** [comment] 2022-08-03 10:15
Fixed in newest Crafting Tweaks version

**Closed as completed by BlayTheNinth** 2022-08-03 10:15 UTC
Labels: Bug, Crash
