### ISSUE TITLE
[QUILT] Possible compat issue with Farmer's Delight

### ISSUE THREAD

**Issue by Sunconure11** [ModdingForBlockheads/Forbic#37] opened 2022-10-01 23:04 UTC
### Minecraft Version

1.19.x

### Mod Loader

Fabric

### Mod Loader Version

Quilt 0.17.5-beta.2

### Mod Version

4.5.2+0

### Describe the Issue

The game crashes upon startup. There isn't much more to describe.

### Logs

https://pastebin.com/HnscuQeS

**Comment by BlayTheNinth** [comment] 2022-10-13 15:11
Same issue as #36. If this happens only on Quilt and not on Fabric, it should be reported to Quilt. I can't see anything obvious that would be causing this in either of the three code bases.

**Comment by SplendidAlakey** [comment] 2023-01-22 13:08
This is actually a complete duplicate of #36, you can see Terrestria in the logs. Farmer's Delight works just fine on Quilt with Balm.

`FabricCropBlockMixin` seems to fail on Quilt, if any other mod also mixins into CropBlock. I've summed up my findings over at Quilt's repo: https://github.com/QuiltMC/quilt-loader/issues/129#issuecomment-1399479354

Edit: Forge seems to be affected by the same issue https://github.com/TwelveIterationMods/Balm/issues/38

**Comment by BlayTheNinth** [comment] 2023-01-23 11:25
Duplicate of #36

**Closed as not planned by BlayTheNinth** 2023-01-23 11:25 UTC
Labels: Bug, Caused by Another Mod, Duplicate, Crash
